#!/bin/sh

# nicenesses range from -20 (most favorable scheduling) to 19 (least favorable)
NICE=19

# 0 for none, 1 for real time, 2 for best-effort, 3 for idle
IONICE_CLASS=2

# 0-7 (for IONICE_CLASS 1 and 2 only), 0=highest, 7=lowest
IONICE_PRIORITY=7

CMD_RUN="/usr/bin/freshclam"

[ -x /usr/bin/nice ] && CMD_RUN="/usr/bin/nice -n ${NICE:-19} ${CMD_RUN}"
[ -x /usr/bin/ionice ] && CMD_RUN="/usr/bin/ionice -c ${IONICE_CLASS:-2} -n ${IONICE_PRIORITY:-7} ${CMD_RUN}"
${CMD_RUN}

exit 0
