#!/bin/sh

. ./functions.sh

lsblk -naro NAME | tr ' ' '\r' |
while IFS=$'\r' read -r NAME
do
	TEMP="$(get_part_info "/dev/${NAME}")"
	echo "${TEMP}"
#	echo "NAME=$(get_part_param 'NAME' <<< "${TEMP}")"
#	echo "ID_PART_ENTRY_NAME=$(get_part_param 'ID_PART_ENTRY_NAME' <<< "${TEMP}")"
#	echo "ID_FS_LABEL=$(get_part_param 'ID_FS_LABEL' <<< "${TEMP}")"
#
	echo '-----------------'
done
runs()
{
	local NAME

	local ITEMS="$(lsblk -nrao NAME | tr ' ' '\r' |
	while IFS=$'\r' read -r NAME
	do
		local TEMP="$(get_part_info "/dev/${NAME}")"

		local MOUNTPOINT="$(get_part_param 'MOUNTPOINT' <<< "${TEMP}")"
		local ID_FS_TYPE="$(get_part_param 'ID_FS_TYPE' <<< "${TEMP}")"

		if [[ ! -n "${MOUNTPOINT}" ]] && [[ "${ID_FS_TYPE}" == 'swap' ]]
		then
			local DEVNAME="$(get_part_param 'DEVNAME' <<< "${TEMP}")"

			local PART_TABLE_TYPE_NAME="$(get_part_param 'PART_TABLE_TYPE_NAME' <<< "${TEMP}")"
			local SIZE="$(get_part_param 'SIZE' <<< "${TEMP}")"
			local ID_FS_LABEL="$(get_part_param 'ID_FS_LABEL' <<< "${TEMP}")"

			echo -e "'${DEVNAME}' '\"${PART_TABLE_TYPE_NAME}\" ${SIZE} ${ID_FS_TYPE} \"${ID_FS_LABEL}\"'"
		fi

	done)"
	echo "${ITEMS}"
}
runs